// src/lib/aerolux/pythongen.js
// python batch generator/automater for Aerolux gradients

// stop serialisation ────────────────────────────────────────────────

/**
 * Converts a stop object into a Python stop() call string.
 * @param {object} s        - stop object { pos, ci }
 * @param {Array}  palette  - resolved palette array { i, r, g, b }[]
 * @param {Function} toHex  - toHex(r,g,b) from palette.js
 * @param {string} indent   - indentation prefix
 */
export function stopToCode(s, palette, toHex, indent = '        ') {
  const c   = palette[s.ci] || palette[0];
  const pos = Math.round(s.pos * 1000) / 1000;
  return `${indent}stop(${pos.toFixed(3)}, ${c.r}, ${c.g}, ${c.b}),  # ${toHex(c.r,c.g,c.b)} pal#${s.ci}`;
}

export function generatePythonScript(paletteLines, outDir, generatedJob, examplesBlock) {
  return `#!/usr/bin/env python3
"""
╔═══════════════════════════════════════════════════════════════════╗
║                    AEROLUX BATCH GENERATOR                        ║
║                     Generated by Aerolux                          ║
╚═══════════════════════════════════════════════════════════════════╝
usage:
    python aerolux_batch.py                    # run all jobs
    python aerolux_batch.py --preview          # preview without writing
    python aerolux_batch.py --out ./my_folder  # override output dir

you will need python 3.8 minimally to run this code.
"""

import os, sys, math, colorsys, argparse, itertools
from typing import List, Tuple, Optional, Dict, Any
from dataclasses import dataclass, field
from copy import deepcopy

# palette
RAW_PALETTE = [
    (0,0,0),(63,63,63),(53,53,53),(45,45,45),(37,37,37),(30,30,30),(22,22,22),(0,0,0),
    (63,0,0),(47,0,0),(32,0,0),(16,0,0),(63,25,0),(47,19,0),(32,12,0),(16,6,0),
    (63,50,0),(47,38,0),(32,25,0),(16,12,0),(50,63,0),(38,47,0),(25,32,0),(12,16,0),
    (25,63,0),(19,47,0),(12,32,0),(6,16,0),(0,63,0),(0,47,0),(0,32,0),(0,16,0),
    (0,63,25),(0,47,19),(0,32,12),(0,16,6),(0,63,50),(0,47,38),(0,32,25),(0,16,12),
    (0,50,63),(0,38,47),(0,25,32),(0,12,16),(0,25,63),(0,19,47),(0,12,32),(0,6,16),
    (0,0,63),(0,0,47),(0,0,32),(0,0,16),(25,0,63),(19,0,47),(12,0,32),(6,0,16),
    (50,0,63),(38,0,47),(25,0,32),(12,0,16),(63,0,50),(47,0,38),(32,0,25),(16,0,12),
    (63,0,25),(47,0,19),(32,0,12),(16,0,6),(63,16,16),(47,12,12),(32,8,8),(16,4,4),
    (63,34,16),(47,26,12),(32,17,8),(16,8,4),(63,53,16),(47,40,12),(32,26,8),(16,13,4),
    (53,63,16),(40,47,12),(26,32,8),(13,16,4),(34,63,16),(26,47,12),(17,32,8),(8,16,4),
    (16,63,16),(12,47,12),(8,32,8),(4,16,4),(16,63,34),(12,47,26),(8,32,17),(4,16,8),
    (16,63,53),(12,47,40),(8,32,26),(4,16,13),(16,53,63),(12,40,47),(8,26,32),(4,13,16),
    (16,34,63),(12,26,47),(8,17,32),(4,8,16),(16,16,63),(12,12,47),(8,8,32),(4,4,16),
    (34,16,63),(26,12,47),(17,8,32),(8,4,16),(53,16,63),(40,12,47),(26,8,32),(13,4,16),
    (63,16,53),(47,12,40),(32,8,26),(16,4,13),(63,16,34),(47,12,26),(32,8,17),(16,4,8),
]

# colour math functions
def to8(v): return round(v * 255 / 63)
def from8(v): return v * 63 / 255
def to_hex(r,g,b): return f"#{ to8(r):02x}{to8(g):02x}{to8(b):02x}"
def rgb6_to_hsl(r,g,b):
    h,l,s = colorsys.rgb_to_hls(r/63,g/63,b/63); return h,s,l
def hsl_to_rgb6(h,s,l):
    r,g,b = colorsys.hls_to_rgb(h,l,s); return r*63,g*63,b*63
def rgb6_to_lab(r,g,b):
    def lin(c): c/=255; return ((c+0.055)/1.055)**2.4 if c>0.04045 else c/12.92
    R,G,B=lin(to8(r)),lin(to8(g)),lin(to8(b))
    X=R*0.4124+G*0.3576+B*0.1805; Y=R*0.2126+G*0.7152+B*0.0722; Z=R*0.0193+G*0.1192+B*0.9505
    def f(t): return t**(1/3) if t>0.008856 else 7.787*t+16/116
    return 116*f(Y)-16, 500*(f(X/0.95047)-f(Y)), 200*(f(Y)-f(Z/1.08883))
def rgb_dist(a,b): return math.sqrt(sum((x-y)**2 for x,y in zip(a,b)))
def lab_dist(a,b): return math.sqrt(sum((x-y)**2 for x,y in zip(a,b)))
def lerp(a,b,t): return a+t*(b-a)
def lerp_rgb(ca,cb,t): return tuple(lerp(a,b,t) for a,b in zip(ca,cb))
def lerp_hsl(ca,cb,t,direction='shortest'):
    ha,sa,la=rgb6_to_hsl(*ca); hb,sb,lb=rgb6_to_hsl(*cb)
    dh=hb-ha
    if direction=='longest':
        if 0<dh<0.5: dh-=1
        if -0.5<dh<0: dh+=1
        if dh==0: dh=1
    else:
        if dh>0.5: dh-=1
        if dh<-0.5: dh+=1
    h=(ha+t*dh)%1.0; s=lerp(sa,sb,t); l=lerp(la,lb,t)
    return hsl_to_rgb6(h,s,l)
def nearest_rgb(target,palette):
    best,bd=0,float('inf')
    for i,c in enumerate(palette):
        if i==0: continue
        d=rgb_dist(target,c)
        if d<bd: bd,best=d,i
    return best
def nearest_lab(target,palette):
    tlab=rgb6_to_lab(*target); best,bd=0,float('inf')
    for i,c in enumerate(palette):
        if i==0: continue
        d=lab_dist(tlab,rgb6_to_lab(*c))
        if d<bd: bd,best=d,i
    return best
def nearest_vivid(target,palette):
    tlab=rgb6_to_lab(*target)
    cands=sorted([(i,lab_dist(tlab,rgb6_to_lab(*c)),rgb6_to_hsl(*c)[1]) for i,c in enumerate(palette) if i!=0],key=lambda x:x[1])
    thresh=cands[0][1]*3+5; close=[c for c in cands if c[1]<=thresh]
    close.sort(key=lambda x:-x[2]); return close[0][0]

# easing functions
def _bounce(t):
    if t<1/2.75: return 7.5625*t*t
    if t<2/2.75: t-=1.5/2.75;  return 7.5625*t*t+0.75
    if t<2.5/2.75: t-=2.25/2.75; return 7.5625*t*t+0.9375
    t-=2.625/2.75; return 7.5625*t*t+0.984375
def _elastic(t):
    if t in(0,1): return t
    return -(2**(10*t-10))*math.sin((t*10-10.75)*(2*math.pi)/3)
EASINGS={
    'linear':lambda t:t,'ease_in':lambda t:t*t,'ease_out':lambda t:1-(1-t)**2,
    's_curve':lambda t:2*t*t if t<0.5 else 1-2*(1-t)**2,
    'cubic_in':lambda t:t**3,'cubic_out':lambda t:1-(1-t)**3,
    'sine_in':lambda t:1-math.cos(t*math.pi/2),'sine_out':lambda t:math.sin(t*math.pi/2),
    'sine_both':lambda t:-(math.cos(math.pi*t)-1)/2,
    'expo_in':lambda t:0 if t==0 else 2**(10*t-10),'expo_out':lambda t:1 if t==1 else 1-2**(-10*t),
    'bounce':_bounce,'elastic':_elastic,
}

# data classes
@dataclass
class Stop:
    pos:float; colour:Optional[Tuple]=None; palette_idx:Optional[int]=None
    def resolve(self,palette): return palette[self.palette_idx] if self.palette_idx is not None else self.colour
def stop(pos,r,g,b): return Stop(pos=pos,colour=(r,g,b))
def stop8(pos,r,g,b): return Stop(pos=pos,colour=(from8(r),from8(g),from8(b)))
def stop_hex(pos,h): h=h.lstrip('#'); r,g,b=int(h[0:2],16),int(h[2:4],16),int(h[4:6],16); return stop8(pos,r,g,b)
def stop_hsl(pos,hd,s,l): r,g,b=hsl_to_rgb6(hd/360,s,l); return Stop(pos=pos,colour=(r,g,b))
def stop_palette(pos,idx): return Stop(pos=pos,palette_idx=idx)

@dataclass
class Tint:
    colour:Tuple; strength:float=0.3; fade:Optional[str]=None
    def strength_at(self,t):
        s=self.strength
        if self.fade=='in': return s*t
        if self.fade=='out': return s*(1-t)
        if self.fade=='centre': return s*(1-abs(t-0.5)*2)
        return s
def tint_hex(h,s=0.3,fade=None): h=h.lstrip('#'); r,g,b=int(h[0:2],16),int(h[2:4],16),int(h[4:6],16); return Tint((from8(r),from8(g),from8(b)),s,fade)
def tint_white(s=0.3,fade=None): return Tint((63,63,63),s,fade)
def tint_black(s=0.3,fade=None): return Tint((0,0,0),s,fade)
def tint_hsl(hd,sat,lig,s=0.3,fade=None): r,g,b=hsl_to_rgb6(hd/360,sat,lig); return Tint((r,g,b),s,fade)
def tint_palette(idx,s=0.3,fade=None): r,g,b=RAW_PALETTE[idx]; return Tint((r,g,b),s,fade)

@dataclass
class Envelope:
    shape:str='none'; attack:float=0.2; release:float=0.2; floor:float=0.0
    custom_pts:List=field(default_factory=list)
    def brightness_at(self,t):
        if self.shape=='none': return 1.0
        if self.shape=='fade_in': return lerp(self.floor,1.0,min(t/max(self.attack,1e-6),1.0))
        if self.shape=='fade_out': return lerp(1.0,self.floor,max((t-(1-self.release))/max(self.release,1e-6),0.0))
        if self.shape=='fade_both':
            a=lerp(self.floor,1.0,min(t/max(self.attack,1e-6),1.0))
            b=lerp(1.0,self.floor,max((t-(1-self.release))/max(self.release,1e-6),0.0))
            return min(a,b)
        if self.shape=='bell': return lerp(self.floor,1.0,math.sin(math.pi*t))
        if self.shape=='valley': return lerp(1.0,self.floor,math.sin(math.pi*t))
        if self.shape=='custom' and self.custom_pts:
            pts=sorted(self.custom_pts,key=lambda p:p[0])
            for i in range(len(pts)-1):
                if pts[i][0]<=t<=pts[i+1][0]:
                    lt=(t-pts[i][0])/(pts[i+1][0]-pts[i][0]+1e-9)
                    return lerp(pts[i][1],pts[i+1][1],lt)
            return pts[-1][1]
        return 1.0

@dataclass
class Variation:
    name_suffix:str=''; hue_shift:float=0.0; sat_mult:float=1.0; lum_mult:float=1.0
    steps:Optional[int]=None; algorithm:Optional[str]=None; easing:Optional[str]=None
    hsl_direction:Optional[str]=None; tint:Optional[Any]=None; envelope:Optional[Any]=None
    stop_overrides:Dict=field(default_factory=dict); extra_stops:List=field(default_factory=list)

@dataclass
class GradientJob:
    name:str; stops:List; steps:int=16; algorithm:str='rgb'; easing:str='linear'
    hsl_direction:str='shortest'; tint:Optional[Any]=None; envelope:Optional[Any]=None
    anti_repeat:bool=True; variations:List=field(default_factory=list)

# engine
def apply_var_to_stop(s,var,palette):
    base=s.resolve(palette)
    if var.hue_shift==0 and var.sat_mult==1.0 and var.lum_mult==1.0: return base
    h,sa,l=rgb6_to_hsl(*base)
    h=(h+var.hue_shift/360)%1.0; sa=max(0.0,min(1.0,sa*var.sat_mult)); l=max(0.0,min(1.0,l*var.lum_mult))
    return hsl_to_rgb6(h,sa,l)

def build_gradient(job,palette,variation=None):
    es=variation.steps if variation and variation.steps else job.steps
    ea=variation.algorithm if variation and variation.algorithm else job.algorithm
    ee=variation.easing if variation and variation.easing else job.easing
    eh=variation.hsl_direction if variation and variation.hsl_direction else job.hsl_direction
    ev=variation.envelope if variation and variation.envelope else job.envelope
    et=(None if (variation and variation.tint is False) else
        (variation.tint if (variation and variation.tint is not None) else job.tint))
    eff_stops=deepcopy(job.stops)
    if variation:
        for idx,ns in variation.stop_overrides.items():
            if idx<len(eff_stops): eff_stops[idx]=ns
        eff_stops.extend(variation.extra_stops)
    resolved=[]
    for s in eff_stops:
        c=(apply_var_to_stop(s,variation,palette) if variation and
           (variation.hue_shift!=0 or variation.sat_mult!=1.0 or variation.lum_mult!=1.0)
           else s.resolve(palette))
        resolved.append((s.pos,c))
    resolved.sort(key=lambda x:x[0])
    if resolved[0][0]!=0.0: resolved[0]=(0.0,resolved[0][1])
    if resolved[-1][0]!=1.0: resolved[-1]=(1.0,resolved[-1][1])
    ease_fn=EASINGS.get(ee,EASINGS['linear']); result=[]
    for i in range(es):
        t=0.0 if es==1 else ease_fn(i/(es-1))
        s0,s1=resolved[0],resolved[-1]
        for j in range(len(resolved)-1):
            if resolved[j][0]<=t<=resolved[j+1][0]: s0,s1=resolved[j],resolved[j+1]; break
        span=s1[0]-s0[0]; lt=0.0 if span<1e-6 else max(0.0,min(1.0,(t-s0[0])/span))
        ca,cb=s0[1],s1[1]
        if ea=='stepped': interp=ca if lt<0.5 else cb
        elif ea=='hsl': interp=lerp_hsl(ca,cb,lt,eh)
        else: interp=lerp_rgb(ca,cb,lt)
        if ev: interp=tuple(c*ev.brightness_at(t) for c in interp)
        if ea=='lab': vel=nearest_lab(interp,palette)
        elif ea=='vivid': vel=nearest_vivid(interp,palette)
        else: vel=nearest_rgb(interp,palette)
        if et:
            s_val=et.strength_at(t)
            if s_val>0:
                pc=palette[vel]; tc=et.colour
                blended=(pc[0]*(1-s_val)+tc[0]*s_val, pc[1]*(1-s_val)+tc[1]*s_val, pc[2]*(1-s_val)+tc[2]*s_val)
                vel=nearest_rgb(blended,palette)
        if job.anti_repeat and result and vel==result[-1][1] and 0<lt<1:
            prev=result[-1][1]; best2,bd2=-1,float('inf')
            for idx,c in enumerate(palette):
                if idx==0: continue
                if idx==prev: continue
                d=rgb_dist(interp,c)
                if d<bd2: bd2,best2=d,idx
            if best2!=-1 and bd2<=rgb_dist(interp,palette[vel])*2.5: vel=best2
        result.append((i,vel))
    return result

# if you are reading this, subscribe to airborneyt

# output
import re
def safe_filename(n): return re.sub(r'[^a-z0-9_\\-]','_',n.lower()).strip('_')
def gradient_to_text(result): return '\\n'.join(f"{s}, {v};" for s,v in result)
def save_gradient(result,name,output_dir,preview=False):
    vels='_'.join(str(v) for _,v in result)
    fp=os.path.join(output_dir,f"{safe_filename(name)}_{vels}")
    if not preview:
        os.makedirs(output_dir,exist_ok=True)
        with open(fp,'w') as f: f.write(gradient_to_text(result))
    return fp
def print_preview(name,result,palette,fp):
    bar=''
    for _,vel in result:
        r,g,b=[round(c*255/63) for c in palette[vel]]
        bar+=f"\\033[48;2;{r};{g};{b}m  \\033[0m"
    print(f"  {name}\\n  {bar}\\n  vels: {' '.join(str(v) for _,v in result)}\\n  → {fp}\\n")
def run_jobs(jobs,output_dir,palette,preview=False):
    total=0
    for job in jobs:
        items=[]
        if not job.variations: items.append((job.name,None))
        else:
            if not job.name.endswith('*'): items.append((job.name,None))
            jn=job.name.rstrip('*')
            for var in job.variations:
                suffix=var.name_suffix or f'_var{len(items)+1}'
                items.append((f"{jn}{suffix}",var))
        for name,var in items:
            result=build_gradient(job,palette,var)
            fp=save_gradient(result,name,output_dir,preview)
            print_preview(name,result,palette,fp)
            total+=1
    print(f"───  {'Would write' if preview else 'Wrote'} {total} gradient(s) to '{output_dir}'  ───")

# ════════════════════════════════════════════════════════════════════
# § BATCH JOBS  ← your generated job is here
# ════════════════════════════════════════════════════════════════════

OUTPUT_DIR = '${outDir}'

BATCH_JOBS = [${generatedJob}${examplesBlock}
]

# ════════════════════════════════════════════════════════════════════
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Aerolux batch gradient generator')
    parser.add_argument('--preview', action='store_true')
    parser.add_argument('--out', default=None)
    args = parser.parse_args()
    out = args.out or OUTPUT_DIR
    pal = list(RAW_PALETTE)
    print(f"\\n{'═'*56}\\n  AEROLUX BATCH  →  '{out}'\\n{'═'*56}\\n")
    run_jobs(BATCH_JOBS, out, pal, preview=args.preview)
`
}
